### 1. Numpy Dimensional Array

In [2]:
import numpy as np

### 1. ndarray np의 차이

In [5]:
l = [1, 2, 3, 4, 5]
l = [i * i for i in l]
l


[1, 4, 9, 16, 25]

In [3]:
n = np.array([1, 2, 3, 4, 5], dtype=int)
n


array([1, 2, 3, 4, 5])

In [4]:
n = np.square(n)
n


array([ 1,  4,  9, 16, 25])

### 1차원 배열(Vector) 만들기

In [6]:
a = np.array((1,2,3,4,5,6,7,8,9,10))
type(a)

numpy.ndarray

In [7]:
a.dtype, a.shape, a.ndim, a.size

(dtype('int32'), (10,), 1, 10)

In [8]:
# 백터화 연산
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
a = np.array([1, 2, 3])
b = np.array([10 ,20 ,30])
c = 2 * a + b
c


array([12, 24, 36])

In [12]:
a == 2, b > 10

(array([False,  True, False]), array([False,  True,  True]))

- 2 차원 배열(Matrix)

In [15]:
c = np.array([[1,2,3], [4,5,6]])          # np.arange(1, 7).reshape(2, 3)
print(c)

[[1 2 3]
 [4 5 6]]


In [16]:
c.dtype,c.shape,c.ndim,c.size

(dtype('int32'), (2, 3), 2, 6)

- 3차원 배열(Tensor)

In [19]:
t = np.arange(1,25).reshape(2, 3, 4)

t

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [20]:
t.dtype,t.shape, t.ndim, t.size

(dtype('int32'), (2, 3, 4), 3, 24)

- 배열의 인덱싱

In [22]:
a

array([1, 2, 3])

In [24]:
a[0], a[2],a[-1]

(1, 3, 3)

In [25]:
c[0,0], c[-1,0], c[1,2]

(1, 4, 6)

- 배열의 슬라이싱

In [27]:
ㅣ = [[1,2,3],[4,5,6],[7,8,9]]
ㅣ[:2]

[[1, 2, 3], [4, 5, 6]]

In [29]:
# 리스트에서는 행과 열로 동시에 슬라이싱이 안된다.
ㅣ[:2][1:]

[[4, 5, 6]]

In [31]:
c = np.arange(1,10).reshape(3,3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
1,4,3,6
c[:-1,::2]

array([[1, 3],
       [4, 6]])

In [36]:
1,7,3,9
c[::2, ::2]

array([[1, 3],
       [7, 9]])

In [38]:
m = np.array([[0,1,2,3,4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])

In [41]:
# 1. 이 행렬에서 값 7 을 인덱싱한다

m[1,2]

7

In [42]:
# 2. 이 행렬에서 값 14 을 인덱싱한다
m[-1,-1]

14

In [43]:
# 3. 이 행렬에서 값 [6,7] 을 인덱싱한다
m[1,1:3]

array([6, 7])

In [44]:
# 4. 이 행렬에서 값 [7, 12] 을 슬라이싱한다
m[1:, 2]

array([ 7, 12])

In [45]:
# 5. 이 행렬에서 [[3,4], [8,9]] 을 슬라이싱한다.
m[-1:, 3:]

array([[13, 14]])

- 배열 인덱싱(Fancy indexing)

In [53]:
# idx 값이 True/False 이면 True 값이 있는 곳의 원소만 통과(filter)

a = np.array([1,2,3,4,5,6,7,8,9,10])
idx = np.array([True, False,True, False,True, False,True, False,True, False])
a[idx]

array([1, 3, 5, 7, 9])

In [49]:
a % 2 == 1

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [52]:
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

In [51]:
# idx 값이 정수값(인덱스)이면 해당 인덱스의 원소가 선택됨
idx = np.array([1, 3, 5, 7, 9])
a[idx]

array([ 2,  4,  6,  8, 10])

- 연습 문제 3

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [65]:
# 1. 이 배열에서 3의 배수를 찾아라
a[a % 3 == 0]

array([3, 6, 9])

In [66]:
# 2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
a[a % 4 == 1]

array([1, 5, 9])

In [68]:
# 3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
a[]

SyntaxError: invalid syntax (97317666.py, line 2)