5. 난수 발생과 카운팅

In [1]:
import numpy as np

- Seed 설정

In [3]:

np.random.seed(2023)
np.random.random(5)

array([0.3219883 , 0.89042245, 0.58805226, 0.12659609, 0.14134122])

- 데이터의 순서 바꾸기

In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.random.shuffle(x)
x

array([7, 4, 3, 2, 8, 9, 1, 6, 0, 5])

- 데이터의 샘플링

In [12]:
np.random.choice(5,5, replace=False)

array([1, 3, 0, 2, 4])

In [14]:
x = np.random.randint(1, 100, 10)
x

array([48, 66, 72, 23, 54,  8, 46, 26, 35, 50])

In [15]:
np.random.choice(x, 5, replace=False)

array([72, 50, 66, 35,  8])

- 난수 생성

In [17]:
# random() - Uniform 분포, 0
np.random.random(10)

array([0.59310305, 0.9147945 , 0.25066314, 0.07173657, 0.30121014,
       0.26788935, 0.72442186, 0.4034967 , 0.47762815, 0.21232418])

In [21]:
# randin(low, high , N) - [low, high)
np.random.randint(1, 7, 10)

array([6, 3, 6, 6, 3, 2, 3, 3, 1, 5])

In [19]:
# normal(평균, 표준편차, N)
np.random.normal(170, 10, 10)

array([187.78760021, 181.81489725, 177.68732532, 158.53272461,
       184.18333755, 161.0243845 , 180.08707685, 162.23677283,
       178.41253853, 180.50933798])

In [23]:
# randn(N) - 표준 정규분포 N (0,1)
np.random.randn(10)

array([-8.56063595e-05,  7.58645897e-01, -2.73056055e-01, -2.26094192e+00,
        2.02856304e-01,  6.24369780e-03, -6.97896348e-01,  1.31799990e+00,
       -1.33051470e+00,  1.84333885e+00])

In [24]:
# binomial(시도횟수, 평균, N) - 이항분포 B(N, p)
np.random.binomial(10, 0.5, 20).reshape(4,5)

array([[3, 5, 4, 2, 5],
       [7, 4, 7, 5, 2],
       [4, 5, 2, 6, 4],
       [6, 6, 4, 6, 5]])

In [26]:
# 가설 검정 : t - 검정
# standard_t (자유도, N)
np.random.standard_t(2, 10)

array([ 0.04732302,  1.20638923, -0.55560115,  0.23969575,  2.6474858 ,
        0.11196557,  2.47395645, -1.38920435, -0.87036697,  0.37764753])

- 연습 문제 3.5.1

In [31]:
# 1. 동전을 10번 던져 앞면(숫자 1), 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성
np.random.binomial(1, 0.5, 10)

array([0, 0, 1, 1, 1, 1, 0, 0, 0, 0])

In [32]:
# 2. 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
np.mean(np.random.randint(1, 7 ,100))

3.27

- 연습 문제 3.5.2

In [61]:
# 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0% 이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라.
price = 10000
random_numbers = np.random.normal(0, 0.01, 5)
daily_returns = (random_numbers + 0.5) * 10
for daily_return in daily_returns:
    price *= (1 + daily_return / 100)
    print(price)

10496.273460490147
11022.563786979645
11566.345546063892
12156.47936022542
12758.512897964087


In [62]:
rate = np.random.normal(0, 0.01, 5)
rate

array([-0.01024022, -0.00242296, -0.00502113,  0.00225604, -0.00510949])

In [63]:
price = 10000
price = price + price * rate[0]
int(np.round(price))

9898

In [71]:
price = 10000
for i in range(5):
    price = price * (1 + rate[i])
    price = int(np.round(price))
    print(price, end = ' ')

9898 9874 9824 9846 9796 

In [72]:
# list 로 해결
np.random.seed(2023)
rate = np.random.normal(0, 0.01, 250)

In [73]:
# 1. 리스트로 해결
price = 10000
price_list = []
for i in range(250):
    price = price * (1 + rate[i])
    price = int(np.round(price))
    price_list.append(price)

price_array = np.array(price_list)
price_array[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

In [76]:
# 2. 어레이로 해결
price_array2 = np.zeros(250, dtype=int)
price = 10000
for i in range(250):
    price = price * (1 + rate[i])
    price = int(np.round(price))
    price_array2[i] = price

price_array2[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

- 데이터 카운팅

In [78]:
dices = np.random.randint(1, 7, 100)
np.unique(dices)

array([1, 2, 3, 4, 5, 6])

In [82]:
np.unique(dices)


array([1, 2, 3, 4, 5, 6])

In [83]:
indices, count = np.unique(dices, return_counts=True)
indices, count

(array([1, 2, 3, 4, 5, 6]), array([ 9, 24, 24, 13, 15, 15], dtype=int64))

In [85]:
indices * count

array([ 9, 48, 72, 52, 75, 90], dtype=int64)

In [86]:
np.sum(indices * count) / np.sum(count)

3.46

In [93]:
np.mean(dices)

3.46

In [96]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [97]:
index, count

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1], dtype=int64))

In [98]:
np.bincount(dices, minlength=6)

array([ 0,  9, 24, 24, 13, 15, 15], dtype=int64)